faction-limit: 30
faction-world: 'world'
pvp-timer: 60
pvp-timer-message-hit: '&d%player% has tagged you for %timer%'
pvp-timer-message-damager: '&4you have tagged %player% has tagged you for %timer%'
invaild-characters: '&cCant use those characters in your faction name'
name-length: '&cYour faction name must be between 3 - 12 characters'
faction-exists: '&cA faction by that name already exists'
faction-created: '&a%player% &ehas created the faction &6&l%faction%'
faction-disbanded: '&cFaction &l%faction% &cwas disbanded'
player-invited: '&3%player% &bhas been invited to join the faction'
player-uninvited: '&4%player% &chas been uninvited from joining your faction'
player-join-faction: '&a&l%player% &bhas joined the faction'
player-leave-faction: '&c&l%player% &chas left the faction'
make-leader: '&6&l%player% &ehas made &c&l%target% &ethe leader'
make-captain: '&6&l%player% &ehas made &c&l%target% &ethe captain'
demote-captain: '&6&l%player% &ehas demoted &c&l%target%'
revoke-invite: '&c%faction% &ehas revoked your invite to join their faction'
enter-friendly-claim: '&eYou have entered the claim of &a%faction% &7(%dtr%) (&cDeathban&7)'
leave-enemy-claim: '&eYou have left the claim of &c%faction% &7(%dtr%) (&cDeathban&7)'
leave-friendly-claim: '&eYou have left the claim of &a%faction% &7(%dtr%) (&cDeathban&7)'
enter-enemy-claim: '&eYou have entered the claim of &c%faction% &7(%dtr%) (&cDeathban&7)'
enter-safezone: '&eYou have entered &a&l%faction% &7(&aSafezone&7)'
enter-warzone: '&eYou have entered &a&l%faction% &7(&cDeathban&7)'
leave-safezone: '&eYou have left &a&l%faction% &7(&aSafezone&7)'
leave-warzone: '&eYou have left &a&l%faction% &7(&cDeathban&7)'
death-message: '&4&l%player% &chas died &7(&6%dtr%&7)'
same-faction: '&cCant hit &e%player% &cbecause you are in the same faction'
other-inside-safezone: '&c%player% &eis inside a no PvP zone'
self-inside-safezone: '&cCant hit %player% while inside safezone'
interact-in-claim:
  - CHEST
  - ENDER_CHEST
  - BREWING_STAND
  - FENCE_GATE
  - TRAPPED_CHEST
  - WOOD_BUTTON
  - STONE_BUTTON
  - FURNACE
  - TRAPPED_DOOR
  - BEACON
  - DIODE_BLOCK_OFF
  - DIODE_BLOCK_ON
  - REDSTONE_COMPARATOR_OFF
  - REDSTONE_COMPARATOR_ON
  - WOODEN_DOOR
  - HOPER
  - LEVER
  - ANVIL
  - ENCHANTMENT_TABLE
  - DROPPER
  - DISPENSER
  - JUKEBOX