faction-limit: 30
faction-world: 'world'
interact-in-claim:
  - CHEST
  - ENDER_CHEST
  - BREWING_STAND
  - FENCE_GATE
  - TRAPPED_CHEST
  - WOOD_BUTTON
  - STONE_BUTTON
  - FURNACE
  - TRAPPED_DOOR
  - BEACON
  - DIODE_BLOCK_OFF
  - DIODE_BLOCK_ON
  - REDSTONE_COMPARATOR_OFF
  - REDSTONE_COMPARATOR_ON
  - WOODEN_DOOR
  - HOPER
  - LEVER
  - ANVIL
  - ENCHANTMENT_TABLE
  - DROPPER
  - DISPENSER
  - JUKEBOX