name: Factions
main: me.iran.factions.Factions
version: 1.0
softdepend: [Vault]
commands:
  team:
    description: create a team
    aliases: [t,f, faction]
  systemfaction:
    aliases: [sys, sf]
    description: create a system factions
    
