name: Factions
main: me.iran.factions.Factions
version: 1.0
author: Irantwomiles
softdepend: [Vault]
commands:
  faction:
    description: create a faction
    aliases: [t,f, team]
  systemfaction:
    aliases: [sys, sf]
    description: create a system factions
  factionadmin:
    aliases: [fa]
    description: control player factions using a set of commands
    
